"""Report generation: Markdown, HTML, PDF (ReportLab), DOCX via Jinja2."""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Template

from config.settings import settings

logger = logging.getLogger(__name__)

MD_TEMPLATE = """\
# 📊 Autonomous Analytics Agents — Research & Analytics Report

**Generated:** {{ timestamp }}
**Confidence Score:** {{ confidence }}/100

---

## Executive Summary

{{ executive_summary }}

---

## 🔑 Key Metrics

{% for kpi in kpis %}
- **{{ kpi.label }}**: {{ kpi.value }}
{% endfor %}

---

## 🔎 Findings

{% for f in findings %}
- {{ f }}
{% endfor %}

---

## ⚠️ Risks

{% for r in risks %}
- {{ r }}
{% endfor %}

---

## 💡 Opportunities

### Revenue
{% for o in opportunities.revenue %}
- {{ o }}
{% endfor %}

### Cost Savings
{% for o in opportunities.cost_savings %}
- {{ o }}
{% endfor %}

### Efficiency
{% for o in opportunities.efficiency %}
- {{ o }}
{% endfor %}

---

## ✅ Recommendations

### Short-term
{% for r in recommendations.short_term %}
- {{ r }}
{% endfor %}

### Long-term
{% for r in recommendations.long_term %}
- {{ r }}
{% endfor %}

---

{% if research_synthesis %}
## 🌐 Web Research Synthesis

{{ research_synthesis }}
{% endif %}

---

{% if ml_results %}
## 🤖 Machine Learning Results

{% for name, res in ml_results.items() %}
- **{{ name }}**: {{ res }}
{% endfor %}
{% endif %}

---

*Report generated by Autonomous Analytics Agents — Autonomous Multi-Agent Research Platform*
"""


def generate_reports(
    executive_summary: str,
    insights: dict[str, Any],
    kpi_data: dict,
    research_synthesis: str = "",
    ml_results: dict | None = None,
    output_dir: str | Path = "",
) -> dict[str, str]:
    """Render and save reports in MD, HTML, PDF, DOCX formats.

    Returns dict of {format: file_path}.
    """
    out = Path(output_dir or settings.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    safe_ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    # Build KPI list
    kpi_items: list[dict] = []
    kpis = kpi_data.get("kpis", {})
    for k, v in kpis.items():
        if isinstance(v, (int, float, str)) and not isinstance(v, (list, dict)):
            kpi_items.append({"label": k.replace("_", " ").title(), "value": v})
    if not kpi_items:
        kpi_items = [{"label": "Rows", "value": kpis.get("row_count", "N/A")}]

    template = Template(MD_TEMPLATE)
    md_content = template.render(
        timestamp=timestamp,
        confidence=insights.get("confidence_score", "N/A"),
        executive_summary=executive_summary,
        kpis=kpi_items,
        findings=insights.get("findings", []),
        risks=insights.get("risks", []),
        opportunities=insights.get("opportunities", {"revenue": [], "cost_savings": [], "efficiency": []}),
        recommendations=insights.get("recommendations", {"short_term": [], "long_term": []}),
        research_synthesis=research_synthesis,
        ml_results=ml_results or {},
    )

    reports: dict[str, str] = {}

    # Markdown
    md_path = out / f"report_{safe_ts}.md"
    md_path.write_text(md_content, encoding="utf-8")
    reports["md"] = str(md_path)
    logger.info("Markdown report → %s", md_path)

    # HTML
    try:
        import markdown
        html_body = markdown.markdown(md_content, extensions=["tables", "fenced_code"])
        html_full = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Autonomous Analytics Agents Report</title>
<style>body{{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;line-height:1.6;color:#1a1a2e;}}h1{{color:#4f46e5;}}h2{{color:#3730a3;border-bottom:2px solid #e0e7ff;padding-bottom:.25rem;}}code{{background:#f1f5f9;padding:.15rem .3rem;border-radius:4px;}}blockquote{{border-left:4px solid #4f46e5;margin-left:0;padding-left:1rem;color:#475569;}}</style></head>
<body>{html_body}</body></html>"""
        html_path = out / f"report_{safe_ts}.html"
        html_path.write_text(html_full, encoding="utf-8")
        reports["html"] = str(html_path)
    except ImportError:
        logger.warning("markdown library not installed — skipping HTML report")

    # PDF via ReportLab (simplified)
    try:
        pdf_path = _generate_pdf(md_content, out, safe_ts)
        reports["pdf"] = str(pdf_path)
    except Exception as exc:
        logger.warning("PDF generation failed: %s", exc)

    # DOCX
    try:
        docx_path = _generate_docx(md_content, out, safe_ts)
        reports["docx"] = str(docx_path)
    except Exception as exc:
        logger.warning("DOCX generation failed: %s", exc)

    return reports


def _generate_pdf(md_content: str, out: Path, ts: str) -> Path:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    pdf_path = out / f"report_{ts}.pdf"
    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
    styles = getSampleStyleSheet()
    story = [Paragraph("Autonomous Analytics Agents — Research Report", styles["Title"]), Spacer(1, 12)]

    for line in md_content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            story.append(Paragraph(line[2:], styles["Heading1"]))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], styles["Heading2"]))
        elif line.startswith("### "):
            story.append(Paragraph(line[4:], styles["Heading3"]))
        else:
            # Clean markdown symbols
            clean = line.replace("**", "").replace("*", "").replace("`", "")
            story.append(Paragraph(clean, styles["Normal"]))

    doc.build(story)
    return pdf_path


def _generate_docx(md_content: str, out: Path, ts: str) -> Path:
    from docx import Document as DocxDocument
    from docx.shared import Pt, Inches

    docx_path = out / f"report_{ts}.docx"
    doc = DocxDocument()

    doc.add_heading("Autonomous Analytics Agents — Research Report", 0)

    for line in md_content.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            doc.add_heading(line[2:], 1)
        elif line.startswith("## "):
            doc.add_heading(line[3:], 2)
        elif line.startswith("### "):
            doc.add_heading(line[4:], 3)
        else:
            clean = line.replace("**", "").replace("*", "").replace("`", "")
            p = doc.add_paragraph(clean)
            p.style.font.size = Pt(11)

    doc.save(str(docx_path))
    return docx_path
